Add bzlmod module
bazelbuild/platforms pull request #48
Opened 2022-09-25 10:14 UTC by hanneskaeufler

Unfortunately loading the version from `version.bzl` doesn't work it seems.

See https://github.com/bazelbuild/bazel-central-registry/issues/124

2022-10-04 17:32 UTC, aiuto requested changes

2022-10-04 17:32 UTC, aiuto commented on .bazelci/presubmit.yml
> +    bazel: last_green
Don't bother with bazel:last_green. We should be aligned with the bazel we use for the other tests.

2022-10-04 17:32 UTC, aiuto commented on .bazelci/presubmit.yml
> +  ubuntu2004_last_green_bzlmod:
Just ubuntu2004_bzlmod is fine

2022-10-05 20:12 UTC, hanneskaeufler commented
@aiuto  I addressed the comments, thanks for the review!

2022-11-21 21:26 UTC, aiuto commented
This seems to be done already.

2022-11-21 21:26 UTC, closed without merging