Add rules_license style declaration.
bazelbuild/platforms pull request #57
Opened 2022-12-07 21:53 UTC by aiuto

- Done for both WORKSPACE and bzlmod styles
- The dependency is different because rules_license is not up to date in the BCR. I'll correct that at the next rules_license release.
- There should be a release after this, but it should wait until we can update to the next rules_license release

In spite of the last point, doing this now allows testing as early as possible.

2022-12-07 22:03 UTC, gregestren submitted a review, later dismissed

2022-12-08 15:45 UTC, katre requested changes

2022-12-08 15:45 UTC, katre commented on WORKSPACE
> +    # sha256 = "4865059254da674e3d18ab242e21c17f7e3e8c6b1f1421fffa4c5070f82e98b5",
Can you uncomment this with the correct hash?

2022-12-08 15:45 UTC, katre commented on MODULE.bazel
> +    version = "0.0.8",  # keep in sync with version.bzl
You also need to update version.bzl.

2023-02-09 15:50 UTC, katre approved these changes

2023-02-09 15:56 UTC, aiuto commented
I broke the LGTM with a buildifier run. :-(

2023-02-09 16:02 UTC, katre approved these changes

2023-02-09 16:03 UTC, merged