POC: implement local_config_platform in @platforms
bazelbuild/platforms pull request #86
Opened 2024-03-08 05:11 UTC by Wyverald

2024-03-08 20:07 UTC, Wyverald commented
cc @fmeum @katre @brentleyjones

@katre specifically, do aliases work with platforms? If they don't, the "canonical" host platform will need to be `@bazel_tools//:host_platform` instead of `@platforms//host` (because default flag values can only be stuff inside built-in modules like `@bazel_tools` (and `@local_config_platform` today)) and the migration path is a bit trickier (we'd have to ask people to actually stop using `@local_config_platform//:host` and switch to `@bazel_tools//:host_platform` instead).

2024-03-11 11:21 UTC, katre commented
For future reference: context here is https://github.com/bazelbuild/bazel/issues/8766 and https://bazelbuild.slack.com/archives/CA31HN1T3/p1709673438139349

@Wyverald: There are reasons I have been asking for an actual design for this feature from the beginning of https://github.com/bazelbuild/bazel/issues/8766. We very deliberately have resisted putting complex logic in the `@platforms` repository, because it is foundational to so many other repos (including Bazel itself), and so anything that we add here has a lot of follow-on effects. I'm not opposed to it, but we need to plan for it.

I'd like to, once again, ask people to step back from the fun part of writing code and move to the less fun part of writing and discussing a design document.

2024-03-19 01:58 UTC, Wyverald commented
Design doc: https://docs.google.com/document/d/1g5JAAOfLsvQKBGqzSLFp1hIYFoQsgOslsjaIGV6P7Tk/edit

2024-03-20 22:26 UTC, Wyverald commented
The test I added is a bit ugly, but it works... except on Windows. Not sure what's going on there...

2024-03-21 10:13 UTC, katre requested changes

2024-03-21 10:13 UTC, katre commented on host/BUILD.bazel
There should be an initial comment explaining the purpose of these files.

2024-03-21 10:13 UTC, katre commented on tests/BUILD
As things are currently set up, will these test files be included in the release? We should avoid that if posible.

2024-03-21 10:14 UTC, katre commented
Added @aranguyen as an FYI

2024-03-21 10:15 UTC, katre commented
I don't think the `sh_test` can execute on windows, do our images have bash support anymore?

2024-03-21 11:05 UTC, meteorcloudy commented
> I don't think the sh_test can execute on windows, do our images have bash support anymore?

`sh_test` should work on Windows and we do have MSYS2 available on CI Windows VMs. 

Believe it or not, the shell test was failing because the Windows launcher wasn't built for the shell test, and that's because the [isExecutedOnWindows](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/RuleContext.java;drc=17e855c959edd42f241e2767f7e434d3f452ac34;bpv=1;bpt=1;l=1446?gsn=isExecutedOnWindows&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fgithub.com%2Fbazelbuild%2Fbazel%3Flang%3Djava%3Fpath%3Dcom.google.devtools.build.lib.analysis.RuleContext%23a94f0a8dde309bfecd095864efded204adaaba7117d53326d323bce6a9a5fa60) function is failing when the root module's name is `platforms`!

2024-03-21 12:37 UTC, meteorcloudy commented
When the root module's name is not `platforms`

<img width="1293" alt="image" src="https://github.com/bazelbuild/platforms/assets/4171702/5cb78e0f-f2f9-42ff-8b87-c447f8711d4a">


when it is `platforms`:

<img width="1023" alt="image" src="https://github.com/bazelbuild/platforms/assets/4171702/5ce3f47c-fc7e-4708-ac7e-84f22cdf3e50">

2024-03-21 15:54 UTC, Wyverald commented on host/BUILD.bazel
added a small comment (similar to what's in cpu/BUILD)

2024-03-21 15:55 UTC, Wyverald commented on tests/BUILD
no they won't. but I also realized that the new `host` directory is also not included 😅 fixed.

2024-03-21 15:59 UTC, katre approved these changes

2024-03-21 17:06 UTC, merged

2024-03-29 05:53 UTC, aignas commented
I am trying to use this and I want to build docs with `stardoc` for a library that uses this. Any tips on how to construct the `bzl_library`? I get
```
$ bazel build //docs/sphinx/...
ERROR: /Users/ignas.anikevicius/src/github/aignas/rules_python/docs/sphinx/BUILD.bazel:75:16: in deps attribute of starlark_doc_extract rule //docs/sphinx:_bzl_api_docs_api_extensions_pip.md_stardoc: missing bzl_library targets for Starlark module(s) @@platforms~host_platform~host_platform//:constraints.bzl. Since this rule was created by the macro 'sphinx_stardocs', the error might have been caused by the macro implementation
ERROR: /Users/ignas.anikevicius/src/github/aignas/rules_python/docs/sphinx/BUILD.bazel:75:16: Analysis of target '//docs/sphinx:_bzl_api_docs_api_extensions_pip.md_stardoc' failed
Use --verbose_failures to see the command lines of failed build steps.
ERROR: Analysis of target '//docs/sphinx:_bzl_api_docs_api_extensions_pip.md' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.220s, Critical Path: 0.00s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

The code is in bazelbuild/rules_python#1827.